{{- if .Values.sealedSecrets }}
{{- range $name, $sealedSecret := .Values.sealedSecrets }}
{{- if $sealedSecret.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
  labels:
    {{- include "database-operator.labels" $ | nindent 4 }}
  {{- with $sealedSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      name: {{ $name }}
      {{- if $sealedSecret.template }}
      {{- if $sealedSecret.template.metadata }}
      {{- if $sealedSecret.template.metadata.annotations }}
      annotations:
        {{- toYaml $sealedSecret.template.metadata.annotations | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
    type: {{ $sealedSecret.type | default "Opaque" }}
  encryptedData:
    {{- toYaml $sealedSecret.encryptedData | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
